[
    (field_declaration
        [
            (function_declarator) 
            (reference_declarator
                (function_declarator))
            (pointer_declarator
                (function_declarator))
        ]
    ) 
    (declaration
        [
            (function_declarator) 
            (reference_declarator
                (function_declarator))
            (pointer_declarator
                (function_declarator))
        ]
    )
]@member_function
